version: '3'

services:
  oplatform-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATA_DIR=/app/data
    volumes:
      - oplatform-data:/app/data

volumes:
  oplatform-data:
    driver: local 